name: Build Release APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Build Tools
      run: sdkmanager "build-tools;30.0.3"

    - name: Install Cordova
      run: npm install -g cordova

    - name: Add Android Platform
      run: cordova platform add android@10.1.2

    - name: Install AdMob Plugin
      run: cordova plugin add cordova-plugin-admob-free --variable ADMOB_APP_ID="ca-app-pub-9502060049942116~3355184393" --save

    - name: Build Android Release APK
      run: cordova build android --release -- --extra-gradle-args="-Xmx2048m"

    - name: Upload Release APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Snake-Glow-Release-APK
        path: platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
